version: "5"

networks:
  internal-nw:
    internal: true
  external-nw:
    internal: false

volumes:
  dolibarr-custom:
  dolibarr-docs:
  mysql-data:

services:
    database:
        image: mariadb:latest
        environment:
            MYSQL_DATABASE: dolibarr
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - internal-nw
        volumes:
            - mysql-data:/var/lib/mysql

    web:
        image: if22b190/dolibarr_erp:latest
        environment:
            DOLI_DB_HOST: database
            DOLI_DB_USER: root
            DOLI_DB_PASSWORD: root
            DOLI_DB_NAME: dolibarr
            DOLI_ADMIN_LOGIN: admin
            DOLI_ADMIN_PASSWORD: admin
            DOLI_URL_ROOT: 'http://localhost'
            DOLI_INSTALL_AUTO: 1
            PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
        volumes:
            - dolibarr-docs:/var/www/documents
            - dolibarr-custom:/var/www/html/custom
        ports:
            - "80:80"
        links:
            - database
        networks:
            - internal-nw
            - external-nw