name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}
          tags: ${{ secrets.REPOSITORY_NAME }}:${{ steps.vars.outputs.tag }}